export const APP_FEATURES = [
  {
    id: "1",
    title: "Tailored Just for You",
    description: "Get interview questions and model answers based on your role, experience, and specific focus areas — no more one-size-fits-all content. Enjoy a prep experience that feels like it was built just for you."
  },
  {
    id: "2",
    title: "Learn at Your Own Pace",
    description: "Expand answers only when you're ready. Dive deeper into any concept instantly with AI-powered detailed explanations, ensuring that your learning experience stays smooth, stress-free, and fully controlled."
  },
  {
    id: "3",
    title: "Capture Your Insights",
    description: "Add personal notes to any question and pin important ones to the top — making your learning more organized, memorable, and personalized to your way of thinking and revision."
  },
  {
    id: "4",
    title: "Understand the 'Why' Behind Answers",
    description: "Beyond just answers — unlock detailed concept explanations generated by AI, helping you truly master each topic with logical reasoning and real-world relevance for interviews."
  },
  {
    id: "5",
    title: "Track Your Progress",
    description: "Keep an eye on how you're improving over time with visual progress indicators, smart recommendations, and milestones that motivate you to keep pushing forward with confidence."
  }
];
